name: a1to5x

on:
  workflow_dispatch:
     inputs:
       mode:
         description: 'Download mode(wget,aria2c,curl,axel)'
         required: true
         default: 'aria2c'
       filename:
         description: 'ROM NAME'
         required: false
       filelink:
         description: 'ROM LINK'
         required: true
       artifact:
         description: 'Upload to Artifact'
         required: true
         default: 'true'
       release:
         description: 'Upload to Release'
         required: true
         default: 'true'

jobs:
  a1to5x:
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Initialization environment
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install git openjdk-8-jdk wget curl rsync aria2 python python3 unzip device-tree-compiler brotli simg2img img2simg axel
          pip3 install protobuf
          pip install brotli

      - id: var
        name: Download
        run: |
          echo "Download"
          if [[ ! -z "${{ github.event.inputs.filename }}" ]]; then
              NAME="${{ github.event.inputs.filename }}"
              if [[ ! -z "$(echo ${NAME} | grep ".zip")" ]]; then
                  echo "::set-output name=filename::${NAME%.*}"
                  echo "${{ github.event.inputs.filename }}"
                  filename="${NAME%.*}"
              else
                  echo "::set-output name=filename::${{ github.event.inputs.filename }}"
                  echo "Null value"
                  filename="${{ github.event.inputs.filename }}"
              fi
              echo "filename: $filename"
              if [[ "${{ github.event.inputs.mode }}" == 'wget' ]]; then
                  wget ${{ github.event.inputs.filelink }} -O "${filename}.zip"
              elif [[ "${{ github.event.inputs.mode }}" == 'aria2c' ]]; then
                  aria2c -x16 -j$(nproc) ${{ github.event.inputs.filelink }} -o "${filename}.zip"             
              elif [[ "${{ github.event.inputs.mode }}" == 'curl' ]]; then
                  curl -L ${{ github.event.inputs.filelink }} -o "${filename}.zip"
              elif [[ "${{ github.event.inputs.mode }}" == 'axel' ]]; then
                  axel -n 16 ${{ github.event.inputs.filelink }} -o "${filename}.zip"
              fi             
          else
              if [[ "${{ github.event.inputs.mode }}" == 'wget' ]]; then
                  wget --content-disposition -c ${{ github.event.inputs.filelink }}
              elif [[ "${{ github.event.inputs.mode }}" == 'aria2c' ]]; then
                  aria2c -x16 -j$(nproc) ${{ github.event.inputs.filelink }}             
              elif [[ "${{ github.event.inputs.mode }}" == 'curl' ]]; then
                  curl -OL ${{ github.event.inputs.filelink }}
              elif [[ "${{ github.event.inputs.mode }}" == 'axel' ]]; then
                  axel -n 16 ${{ github.event.inputs.filelink }}
              fi
              NAME="$(ls -lS *.zip | head -1 | awk '{print $9}')"
              if [ ! -z "$NAME" ]; then
                  filename=${NAME%.*}
              else
                  tmp="$(find . -maxdepth 1 -type f -size +500M)"
                  if [ ! -z "$tmp" ]; then
                      ls -al
                      echo "Rename"
                      filename=$(echo $tmp | sed 's#./##')
                      mv $filename ${filename}.zip
                  else
                      echo "Download error"
                      exit 1
                  fi
              fi              
              echo "::set-output name=filename::$filename"
          fi
          ls -al

      - name: Payload Extractor
        run: |
          echo "Payload Dumper"
          unzip ${{ steps.var.outputs.filename }}.zip payload.bin
          rm -rf ${{ steps.var.outputs.filename }}.zip
          python3 update-payload-extractor/extract.py payload.bin --output_dir ./
          ls -al

      - name: Patching Fstab
        run: |
          mkdir system/
          sudo mount system.img system/
          fstab="system/system/vendor/etc/fstab.qcom"
          sudo sed -i 's/,slotselect//g' $fstab
          sudo sed -i 's/,verify//g' $fstab
          sudo sed -i 's/forceencrypt/encryptable/g' $fstab
          sudo sed -i 's/fileencryption=ice/encryptable=footer/g' $fstab
          sudo cp system/system/vendor/etc/fstab.qcom output/fstab.qcom
          cat system/system/vendor/etc/fstab.qcom
          sudo umount system
          sudo rm -rf system
    
      - name: Mkbootimg
        run: |
          echo "mkbooting"
          mv boot.img mkbootimg/
          cd mkbootimg
          ./mkboot boot.img boot
          rm boot.img
          cd boot
          ls -al
          cd ../../

      - name: Patching device tree blobs
        run: |
          mv mkbootimg/boot/kernel ./image.gz-dtb
          ./split-appended-dtb image.gz-dtb
          ls -al
          rm image.gz-dtb
          temp=$(ls -lS *.dtb | head -1 | awk '{print $9}')
          echo temp: $temp
          dtb=${temp##* }
          dts=${dtb%.*}.dts
          echo dtb: $dtb
          echo dts: $dts
          dtc -q -I dtb -O dts -o $dts $dtb
          rm $dtb
          echo rm: $dtb
          sed -i '/parts/{n;d;}' $dts
          sed -i '/vbmeta/d' $dts
          sed -i '/android,system/{n;d;}' $dts
          sed -i '/android,system/{n;d;}' $dts
          sed -i '/android,system/{n;d;}' $dts
          sed -i '/android,system/d' $dts
          sed -i '/,discard/{n;s/,slotselect//;}' *.dts
          sed -i 'N;/\n.*,slotselect/!P;D' $dts
          sed -i '/,slotselect/{n;d;}' $dts
          sed -i '/,slotselect/{n;d;}' $dts
          sed -i '/,slotselect/d' $dts
          sed -i '/,fstab/r flags.txt' $dts
          sed -i '/,fstab/G' $dts
          sed -i '/android,firmware/{n;d;}' $dts
          sed -i 's/,avb//g' $dts
          sed -i '/,slotselect/{n;s/disable/ok/;}' $dts
          sed -i 's/,slotselect//g' $dts
          dtc -q -I dts -O dtb -o $dtb $dts
          mv *.dts output/
          cat kernel *.dtb > image.gz-dtb
          echo "cat..."
          ls -al
          mv image.gz-dtb mkbootimg/boot/kernel
          sed -i 's/veritykeyid=id:\w*//g' mkbootimg/boot/img_info
          cat mkbootimg/boot/img_info
          cp mkbootimg/boot/img_info output/
          cd mkbootimg
          ./mkboot boot boot.img
          cd ..
          
      - name: MakeMeSAR
        run: |
          mkdir tmp
          mv mkbootimg/boot.img tmp
          cd tmp
          ../magiskboot unpack -h boot.img
          cp -f ../ramdisk-sar.cpio ramdisk.cpio
          ../magiskboot repack boot.img
          ls -al
          cd ..
          
      - name: img2sdat && brotli
        run: |
          pip3 install brotli
          mv tmp/new-boot.img template/boot.img
          mv system.img template/system.img
          cd template
          ../rimg2sdat.py -c system.img
          rm system.img
          rm system.new.dat
          ls -al
          cd ..
          echo "--------------------------------------------"
          mv template ${{ steps.var.outputs.filename }}
          cd ${{ steps.var.outputs.filename }}
          zip -q -r -9 ${{ steps.var.outputs.filename }}.zip *
          cd ..
          mv ${{ steps.var.outputs.filename }}/${{ steps.var.outputs.filename }}.zip ./
          ls -al

      - name: Upload to Artifact
        if: github.event.inputs.artifact == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.var.outputs.filename }}
          path: |
            ${{ steps.var.outputs.filename }}
          retention-days: 7

      - name: Upload to Release
        if: github.event.inputs.release == 'true'
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.var.outputs.filename }}.zip
          name: ${{ steps.var.outputs.filename }}
          tag_name: ${{ github.run_id }}
          body: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE }}
          
      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: 10
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE }}
